services:
  postgres:
    image: postgres:15
    container_name: cloudvault-postgres
    environment:
      POSTGRES_DB: dropbox_db
      POSTGRES_USER: dropbox_user
      POSTGRES_PASSWORD: dropbox_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dropbox_user -d dropbox_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: